name: cbir
channels:
- menpo
- defaults
dependencies:
- bzip2=1.0.6=h9a117a8_4
- ca-certificates=2017.08.26=h1d4fec5_0
- cairo=1.14.12=h77bcde2_0
- certifi=2018.1.18=py35_0
- ffmpeg=3.4=h7264315_0
- fontconfig=2.12.4=h88586e7_1
- freetype=2.8=hab7d2ae_1
- glib=2.53.6=h5d9569c_2
- graphite2=1.3.10=hf63cedd_1
- harfbuzz=1.7.4=hc5b324e_0
- hdf5=1.10.1=h9caa474_1
- icu=58.2=h9c2bf20_1
- intel-openmp=2018.0.0=hc7b2577_8
- jasper=1.900.1=hd497a04_4
- jpeg=9b=h024ee3a_2
- libedit=3.1=heed3624_0
- libffi=3.2.1=hd88cf55_4
- libgcc-ng=7.2.0=h7cc24e2_2
- libgfortran-ng=7.2.0=h9f7466a_2
- libopus=1.2.1=hb9ed12e_0
- libpng=1.6.34=hb9fc6fc_0
- libprotobuf=3.4.1=h5b8497f_0
- libstdcxx-ng=7.2.0=h7a57d05_2
- libtiff=4.0.9=h28f6b97_0
- libvpx=1.6.1=h888fd40_0
- libxcb=1.12=hcd93eb1_4
- libxml2=2.9.7=h26e45fe_0
- mkl=2018.0.1=h19d6760_4
- ncurses=6.0=h9df7e31_2
- numpy=1.14.1=py35ha266831_2
- opencv=3.3.1=py35h6cbbc71_1
- openssl=1.0.2n=hb7f436b_0
- pcre=8.41=hc27e229_1
- pip=9.0.1=py35_5
- pixman=0.34.0=hceecf20_3
- python=3.5.4=hc3d631a_27
- readline=7.0=ha6073c6_4
- setuptools=38.5.1=py35_0
- sqlite=3.22.0=h1bed415_0
- tk=8.6.7=hc745277_3
- wheel=0.30.0=py35hd3883cf_1
- xz=5.2.3=h55aa19d_2
- zlib=1.2.11=ha838bed_2
- cyvlfeat=0.4.6=py35_0
- vlfeat=0.9.20=1